### ISSUE TITLE
Handle errors more gracefully

### ISSUE THREAD

**Issue by jordanryanmoore** [jordanryanmoore/homebridge-scout#29]
Example: If the API call to set the target security system mode fails, it crashes Homebridge. This should log an error, and potentially flag the accessory with a fault (or update reachability?).

**Comment by Tom2527** [comment]
Exceptions and errors I have noticed so far:

1/ during loading time
[ScoutAlarm] StatusCodeError: 429 - {"status":429,"error":"Rate limit exceeded, retry in 2 minutes"}
    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-scout/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-scout/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-scout/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-scout/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-scout/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-scout/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

2/ at runtime (without any obvious consequences)
[Config] [homebridge-scout] Error: ESOCKETTIMEDOUT

**Comment by jordanryanmoore** [comment]
The first error (429 Rate limit exceeded) I've only ever seen when starting the plugin repeatedly over a short period of time, and it's because their authentication endpoint has rate limiting. Do you recall if you had been restarting it repeatedly?

This could be mitigated by caching the authentication token to disk, but I'm hesitant to do that because 1) I don't like saving secrets to disk and 2) it opens the door to all sorts of potential filesystem permissions issues.

I have zero idea what happened with the second error. Based on the format, it's actually something logged by the `Config` plugin, not this one.

**Comment by Tom2527** [comment]
That’s probably it. I was restarting a lot when testing this plugin. 
The error and stack trace were pretty huge, and contain the password in plain view, multiple times. Doesn’t bother me and this error will be very rare, but maybe a more elegant error message could be displayed.

**Comment by jordanryanmoore** [comment]
The original intent of this issue was to ensure that runtime errors didn't crash Homebridge. That was resolved at some point during the refactor to TypeScript.

I'm torn on how to log errors. The stack traces are useless (because the code is all callbacks and async), so the request/response details are necessary to be of any usefulness in debugging.

**Comment by jordanryanmoore** [comment]
I'm resolving this issue. I'll reopen another to address private information potentially being leaked in log statements.
