### ISSUE TITLE
Motion Sensor Support

### ISSUE THREAD

**Issue by jordanryanmoore** [jordanryanmoore/homebridge-scout#4]

**Comment by Tom2527** [comment]
I’m excited to install this plugin soon. Would be great if it also supports motion sensors. I have one, so I can test it out if that helps.

**Comment by jordanryanmoore** [comment]
I have a pull request for motion sensor support, but it’s outdated. I’ll update it in the next couple of days and can give you instructions to test it out.

**Comment by jordanryanmoore** [comment]
Ok, I've updated the pull request.

1. If you haven't already, install homebridge (see https://www.npmjs.com/package/homebridge#installation). 
2. If you've already installed `homebridge-scout`, uninstall it: `npm uninstall -g homebridge-scout`
3. Check out the pull request: `git clone git@github.com:jordanryanmoore/homebridge-scout.git`
4. Change to the new local directory: `cd homebridge-scout`
5. Install the plug-in: `npm install -g`
6. If you haven't already, configure the plug-in via homebridge's `config.json` per https://www.npmjs.com/package/homebridge-scout#configuration.
7. Run `homebridge`.

Please try the motion sensor and (any other sensors you might have) and report back which ones work or don't. Thanks so much for your help!

**Comment by Tom2527** [comment]
I don't know if I did anything wrong but in step 3 I get the following error:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jordanryanmoore** [comment]
I've updated step 3, so please try again. 🤦‍♂️

**Comment by Tom2527** [comment]
The motion sensor is added to HomeKit. As soon as motion is detected, it crashes HomeBridge. 

[12/31/2019, 10:26:36 AM] [ScoutAlarm] Device [0a70080064100450d80fa000a0000100] triggered event fired.
[12/31/2019, 10:26:36 AM] ReferenceError: device is not defined
    at /home/pi/homebridge-scout/lib/device.js:168:85
    at Array.forEach (<anonymous>)
    at /home/pi/homebridge-scout/lib/device.js:146:28
    at Array.forEach (<anonymous>)
    at Device.getCharacteristicValues (/home/pi/homebridge-scout/lib/device.js:145:22)
    at Device.onDeviceTrigger (/home/pi/homebridge-scout/lib/device.js:102:23)
    at /home/pi/homebridge-scout/lib/scout-platform.js:89:24
    at PrivateChannel.module.exports.Dispatcher.emit (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:7237:33)
    at PrivateChannel.module.exports.Channel.handleEvent (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:8091:18)
    at /home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:10148:29
    at ConnectionManager.module.exports.Dispatcher.emit (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:7237:33)
    at message (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:8631:23)
    at Connection.module.exports.Dispatcher.emit (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:7237:33)
    at message (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:7765:27)
    at TransportConnection.module.exports.Dispatcher.emit (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:7237:33)
    at TransportConnection.module.exports.TransportConnection.onMessage (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:7431:14)
    at Client.socket.onmessage (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:7448:19)
    at Client.dispatchEvent (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:4066:30)
    at Client._receiveMessage (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:3257:10)
    at Client.<anonymous> (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:3157:49)
    at Client.emit (events.js:215:7)
    at Client.<anonymous> (/home/pi/homebridge-scout/node_modules/pusher-js/dist/node/pusher.js:3768:14)
[12/31/2019, 10:26:36 AM] Got SIGTERM, shutting down Homebridge...

**Comment by jordanryanmoore** [comment]
I just made a fix to the pull request. Starting after step 4, you should be able to run `git pull` and continue from there.

**Comment by Tom2527** [comment]
I can confirm motion sensor works perfect with this fix.

**Comment by jordanryanmoore** [comment]
Awesome! I'll get this cleaned up and merged to master… hopefully in the next day or two.

**Comment by jordanryanmoore** [comment]
Released in 0.3.0…
